#!/usr/bin/env node
var spawn = require('child_process').spawn;
var fs = require('fs');
var semver = require('semver');
var Task = require('shell-task');

if(!process.argv[2]) {
	// catch if no version number provided
	console.log('Please provide a version number.');
} else if(process.argv[3]) {
	// catch if too many inputs provided
	console.log('\n Too many inputs. Please use the format: \n\n \t\t $ ./nvmvm 0.29 \n');
} else {
	var version = process.argv[2];

	if(!semver.valid(version)) {
		console.log('Version number invalid. Version number should look like this: "0.29.0"');
	} else {
		new Task('curl -O https://raw.githubusercontent.com/creationix/nvm/v' + version + '/install.sh')
		.then(function(next) {
			fs.readFile('install.sh', 'utf8', function(err, data) {
				if (err) throw err;
				if(data === 'Not Found') {
					console.log('That version of NVM appears not to exist. Aborting.');
					fs.unlink('install.sh');
					process.exit();
				} else next()
			})
		})
		.then('bash install.sh')
		.then('rm install.sh')
		.run(
			function(err, next) {
				if(err) {
					console.log('Error encountered in this step. Please try again.');
				} else {
					console.log('NVM install script is finished.')
				}
			}
		);
	}
}
